version: "3.8"
services:
  flask_learning:
    build: .
    image: 'flask_learning:1'
    container_name: 'flask_learning'
    command: >
      sh -c 'cd src && poetry run gunicorn --bind 0.0.0.0:8080 app:app'
    networks:
      - backend
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
      - app_static:/src/static
      - app_media:/src/media
    restart: unless-stopped

  web_server:
    image: 'nginx:alpine3.18'
    container_name: 'web_server'
    networks:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - app_static:/srv/static
      - app_media:/srv/media
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - flask_learning

networks:
  backend:

volumes:
  app_static:
  app_media:
