version: "3.8"
services:
  flask_learning:
    build: .
    image: 'flask_learning:1'
    container_name: 'flask_learning'
    command: >
      sh -c 'cd src && poetry run flask run -h 0.0.0.0 -p 8080 --debug'
    networks:
      - backend
    ports:
      - '80:8080'
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
    restart: unless-stopped

networks:
  backend:

volumes:
  app_static:
  app_media:
